platform :ios, '8.0'
use_frameworks!

target 'YiLianGang' do
pod 'Masonry'
pod 'JSONKit-NoWarning', '~> 1.1'
pod 'SDCycleScrollView','~> 1.64'
pod 'CocoaAsyncSocket'
pod 'AFNetworking'
pod 'WechatOpenSDK'

end
